// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Shitpost struct {
	ID        int64
	Title     string
	Author    string
	Content   string
	Passcode  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
